language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
sudo: false
before_install:
  - lsb_release -a # get info on the operating system
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install wheel
  - wget -q -O - 'https://github.com/obspy/wheelhouse/archive/master.tar.gz' | tar -C /tmp -xzf -
  - pip install --use-wheel --no-index --find-links=/tmp/wheelhouse-master numpy==1.8.2 scipy==0.14.0 lxml sqlalchemy mock nose pyproj
  - pip install --use-wheel --find-links=/tmp/wheelhouse-master coveralls
  - pip install --use-mirrors geographiclib
  - pip install --use-wheel --no-index --find-links=/tmp/wheelhouse-master matplotlib==1.3.1
  - pip install --use-wheel --no-index --find-links=/tmp/wheelhouse-master basemap==1.0.7
  - pip install --use-mirrors flake8
  - pip install --use-mirrors future
  # current pyimgur stable release has a py2.6 incompatibility
  - pip install https://github.com/megies/PyImgur/archive/py26.zip
  - pip freeze
install:
  - git version
  - git fetch origin --tags --unshallow
  - git remote add obspy git://github.com/obspy/obspy.git
  - git fetch obspy --tags
  - git status
  - pip install --no-deps --use-mirrors .
  - git status
script:
  # We change directories to make sure that python won't find the copy
  # of obspy in the source directory, see
  # https://github.com/numpy/numpy/blob/master/.travis.yml#L44
  - mkdir empty
  - cd empty
  - MODULELIST=`python -c "from obspy.core.util import DEFAULT_MODULES as MODULES; print('obspy.' + ',obspy.'.join(MODULES))"`
  - coverage run --rcfile=.coveragerc --source=$MODULELIST -m obspy.core.scripts.runtests -n travis-ci -r
after_success:
  - mv .coverage ../.coverage.empty
  - cd ..
  - coverage combine
  - coveralls
notifications:
    email: false
env:
  global:
    - secure: "qZzgI89uD606mP/l2IDLFmocZ8YFhXRngtWR1wroirhodKzdg89Qax8+UxkdmAyYKgl4+mLA8ZYMpHtojO2l2v96cOJemf/vhdp3Y+HnIURVwoPnPGXCFdC5SlQe6GB+zGqP7EBSRnsib8aexnHY7WFZAb+DOgpKi2gLs2AZeQo="
